%   File: GMEB_ScenarioSpecification.m
%   Copyright (c) <2019> <University of Mons>
%   COLORAMAP Group, Univ. of Mons, Belgium
%   https://sites.google.com/site/nicolasgillis/projects/overview
%
%   Permission is hereby granted, free of charge, to any person
%   obtaining a copy of this software and associated documentation
%   files (the "Software"), to deal in the Software without restriction,
%   including without limitation the rights to use, copy, modify and
%   merge the Software, subject to the following conditions:
%
%   1.) The Software is used for non-commercial research and
%       education purposes.
%
%   2.) The above copyright notice and this permission notice shall be
%       included in all copies or substantial portions of the Software.
%
%   3.) Publication, Distribution, Sublicensing, and/or Selling of
%       copies or parts of the Software requires special agreements
%       with the University of Mons and is in general not permitted.
%
%   4.) Modifications or contributions to the software must be
%       published under this license. The University of Mons
%       is granted the non-exclusive right to publish modifications
%       or contributions in future versions of the Software free of charge.
% 
%   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
%   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
%   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
%   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
%   HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
%   WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
%   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
%   OTHER DEALINGS IN THE SOFTWARE.
%
%   Persons using the Software are encouraged to notify the 
%   COLORAMAP Group, Univ. of Mons, Belgium about bugs. Please reference 
%   the Software in your publications if it was used for them.
% ------------------------------------------------------------------------
% SYNTAX:
% [param, dual_options, primal_options, indVar] =  GMEB_ScenarioSpecification( scenario );
%
% ------------------------------------------------------------------------
% OVERVIEW:
% This function sets the parameters to reproduce the various experiments in
% the paper.
%
% ------------------------------------------------------------------------
% INPUTS:
% scenario  String that specificies the figure to reproduce.
%           'Fig. 3a'/'Fig. 3b'/'Fig. 4a'/'Fig. 4b'
%
% ------------------------------------------------------------------------
% OUTPUTS: 
% param     MATLAB structure that contains the parameters for data
%           generation. Minimally includes the field 'default' with value
%           [true].
%   Fields:
%   'default'           boolean - required
%   'ambient_dims'      scalar - dimension of the ambient space
%   'num_samples_bb'    scalar - # of samples from big ball
%   'num_samples_sb'    scalar - # of samples from small ball
%   'common_dims_bb'    scalar - subspace dimensions shared by all big ball 
%                       points 
%   'common_dims_sb'    scalar - subspace dimensions shared by all small 
%                       ball points
%   'max_dims'          scalar - maximum dimension of any subspace
%   'big_rad'           scalar - radius of big ball
%   'center_sep'        scalar - distance between center of big ball and 
%                       center of small ball
%   'small_rad'         scalar - radius of small ball
%   'noise_var'         scalar - variance of the white Gaussian noise
%   'use_subsample'     boolean - flag to generate additional samples for
%                       the big ball and subsample to increase uniformity
%   'subsample_percent' scalar - percent of total sample to keep as the
%                       subsample (subsample will always have
%                       num_samples_bb points)
%   'eq_variance'       boolean - if true, added subspace dimensions will
%                       include signal of equal variance to correlated 
%                       signals.  otherwise, the extra dimensions are
%                       noise. If true, noise_var = 0; means that there is
%                       no additive gaussian noise in noisy samples but
%                       there is extra dimensions with per component
%                       variance equal to signal dimensions.
%   'dims_bb'           num_samples_bb x 1 double - dimensions of big ball 
%                       points after additional orthogonal dimensions
%                       have been added
%   'dims_sb'           num_samples_sb x 1 double - dimensions of small
%                       ball points after additional orthogonal dimensions
%                       have been added
%   'nonuni'            boolean - if true, extra points will be generated
%                       nonuniformly in the neighborhood of one point on 
%                       the boundary of the large ball.  otherwise, the 
%                       points are approximately uniform
%   'nonuni_amt'        integer - selects the number of extra points that 
%                       come from the nonuniform region
%   'd_type'            string - specifies the distance type to be used.
%                       options are 'DPF' for the squared projection
%                       Frobenious norm or 'DGEO' for the geodesic
%                       distance based on arc-length.
%   'int_pts'           boolean - if true, points will be generated
%                       uniformly within the interior of both balls in the
%                       same ratio as the boundary poitns.  otherwise, the 
%                       points are all on the boundary
%   'int_pts_ratio'     scalar - selects the number of points on the
%                       interior of each ball to be ceil(int_pts_ratio * 
%                       num_samples_bb) (or num_samples_sb respectively).\
%   'dims_bb_int'       ceil(int_pts_ratio * num_samples_bb) x 1 double - 
%                       dimensions of big ball interior points after 
%                       additional orthogonal dimensions have been added
%   'dims_sb_int'       ceil(int_pts_ratio * num_samples_sb) x 1 double - 
%                       dimensions of small ball interior points after 
%                       additional orthogonal dimensions have been added
%
% dual_options      MATLAB structure that contains the parameters for the
%                   GMEB_DualSubgrad algorithm. (May not set all fields)
%   Fields:
%   'tol'               scalar - convergence threshold for the duality gap
%                       and for lack of movement of the dual variable 
%   'step_type'         string - chooses the step size. options are 
%                       'nonSum-sqSum' for per/t or 'nonSum-diminish' for
%                       per/sqrt(t).
%   'useLineSearch'     boolean - line-search flag. if true, algorithm uses
%                       a backtracking line-search in an attempt to find an
%                       iterate that increases the dual cost
%   'initial_soln'      M x 1 double - initial value of the dual variable
%   'maxiter'           scalar - maximum number of outer iterations of 
%                       subgradient algorithm
%   'per'               scalar - step-size parameter, the numerator in the
%                       step-size determines the length of the first step.
%   'growth'            scalar - growth parameter for line-search.
%                       determines the amount that the step-size increases
%                       after a step is accepted in the back-tracking 
%                       line-search. should be in the range (1,2).
% 'findStationaryPoint' boolean - flag that returns solution if dual 
%                       variables don't change in 10 iterations.
%
% primal_options    MATLAB structure that contains the parameters for the
%                   GMEB_Primal algorithm.
%
%   Fields:
%   'default'           boolean - required
%
% indVar            1 x nVar double - the values of the independent
%                   variable for the experiment being run. Either noise 
%                   variance or ambient dimension depending on the
%                   experiment.
% ------------------------------------------------------------------------
% DEPENDENCIES:
% n/a
%
% ------------------------------------------------------------------------
% REFERENCES:
% If this code is useful for you, please cite the paper:
% [1] 	Marrinan, Tim, P.-A. Absil, and Nicolas Gillis
%	"On a minimum enclosing ball of a collection of linear subspaces."
%     	arXiv preprint arXiv:2003.12455 (2020).
%
% ------------------------------------------------------------------------
% CREATED:      21/05/2019 by Tim Marrinan
%
% LAST EDITED:  10/03/2020 by Tim Marrinan
%
% NOTES: 
% -------------------------------------------------------------------------
function [param, dual_options, primal_options, indVar] =  GMEB_ScenarioSpecification( scenario )

param = [];
dual_options = [];
primal_options = [];
indVar = [];

%% Scenario specification
switch lower(scenario)
% -------------------------------------------------------------------------
    case 'custom' % Modify the parameters here to test the code      
        % Data generation paramters
        param       = struct(   'default',false,...
                                'ambient_dims',100, ...
                                'num_samples_bb', 200,...
                                'num_samples_sb', 50,...
                                'common_dims_bb', 1,...
                                'common_dims_sb', 3,...
                                'max_dims', 5,...
                                'big_rad', .5,...
                                'center_sep', (.75)*(.25),...
                                'small_rad', (.25)*(.75)*(.25),...
                                'noise_var', 0.001,...
                                'use_subsample', true,...
                                'subsample_percent', .25,...
                                'eq_variance', false,...
                                'd_type', 'DPF',...
                                'int_pts', false,...
                                'int_pts_ratio', 1,...
                                'nonuni', false,...
                                'nonuni_amt', 50);
        % Proposed method parameters
        dual_options.tol                    = 10^(-4);
        dual_options.step_type              = 'nonSum-diminish';
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 200;
        dual_options.per                    = 5;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = true;
        % Primal method parameters [1]
        primal_options.tol                  = 10^(-10);
        primal_options.maxiter              = 200;
% ------------------------------------------------------------------------
    case 'fig. 3a'      
        % Data generation paramters
        param           = struct(   'default',false,...
                                    'ambient_dims',3, ...
                                    'num_samples_bb', 100,...
                                    'num_samples_sb', 50,...
                                    'common_dims_bb', 1,...
                                    'common_dims_sb',1,...
                                    'max_dims', 1,...
                                    'big_rad', .5,...
                                    'center_sep', (.75)*(.25),...
                                    'small_rad', (.25)*(.75)*(.25),...
                                    'noise_var', 0.01,...
                                    'use_subsample', true,...
                                    'subsample_percent', .5,...
                                    'eq_variance', true,...
                                    'd_type', 'DPF',...
                                    'int_pts', false,...
                                    'int_pts_ratio', 1,...
                                    'nonuni', false,...
                                    'nonuni_amt', 50);
        % Proposed method parameters
        dual_options.tol                    = 10^(-4);
        dual_options.step_type              = 'nonSum-diminish';%'nonSum-sqSum';%
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 200;
        dual_options.per                    = 5;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = false;                                
% ------------------------------------------------------------------------
    case 'fig. 3b'      
        % Data generation paramters
        param           = struct(   'default',false,...
                                    'ambient_dims',3, ...
                                    'num_samples_bb', 100,...
                                    'num_samples_sb', 50,...
                                    'common_dims_bb', 1,...
                                    'common_dims_sb',1,...
                                    'max_dims', 1,...
                                    'big_rad', .5,...
                                    'center_sep', (.75)*(.25),...
                                    'small_rad', (.25)*(.75)*(.25),...
                                    'noise_var', 0.01,...
                                    'use_subsample', true,...
                                    'subsample_percent', .5,...
                                    'eq_variance', true,...
                                    'd_type', 'DPF',...
                                    'int_pts', true,...
                                    'int_pts_ratio', 1,...
                                    'nonuni', false,...
                                    'nonuni_amt', 50);
        % Proposed method parameters
        dual_options.tol                    = 10^(-4);
        dual_options.step_type              = 'nonSum-diminish';%'nonSum-sqSum';%
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 200;
        dual_options.per                    = 5;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = false;                                
% ------------------------------------------------------------------------
    case 'fig. 4a'      
        % Data generation paramters
        param           = struct(   'default',false,...
                                    'ambient_dims',3, ...
                                    'num_samples_bb', 20,...
                                    'num_samples_sb', 0,...
                                    'common_dims_bb', 1,...
                                    'common_dims_sb',1,...
                                    'max_dims', 1,...
                                    'big_rad', .5,...
                                    'center_sep', (.75)*(.25),...
                                    'small_rad', (.25)*(.75)*(.25),...
                                    'noise_var', 0.01,...
                                    'use_subsample', true,...
                                    'subsample_percent', .5,...
                                    'eq_variance', true,...
                                    'd_type', 'DPF',...
                                    'int_pts', false,...
                                    'int_pts_ratio', 1,...
                                    'nonuni', true,...
                                    'nonuni_amt', 50);
        % Proposed method parameters
        dual_options.tol                    = 10^(-4);
        dual_options.step_type              = 'nonSum-diminish';%'nonSum-sqSum';%
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 200;
        dual_options.per                    = 5;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = false;                                
% ------------------------------------------------------------------------
    case 'fig. 4b'      
        % Data generation paramters
        param           = struct(   'default',false,...
                                    'ambient_dims',3, ...
                                    'num_samples_bb', 20,...
                                    'num_samples_sb', 0,...
                                    'common_dims_bb', 1,...
                                    'common_dims_sb',1,...
                                    'max_dims', 1,...
                                    'big_rad', .5,...
                                    'center_sep', (.75)*(.25),...
                                    'small_rad', (.25)*(.75)*(.25),...
                                    'noise_var', 0.01,...
                                    'use_subsample', true,...
                                    'subsample_percent', .5,...
                                    'eq_variance', true,...
                                    'd_type', 'DPF',...
                                    'int_pts', true,...
                                    'int_pts_ratio', 1,...
                                    'nonuni', true,...
                                    'nonuni_amt', 50);
        % Proposed method parameters
        dual_options.tol                    = 10^(-4);
        dual_options.step_type              = 'nonSum-diminish';%'nonSum-sqSum';%
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 200;
        dual_options.per                    = 5;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = false;           
% ------------------------------------------------------------------------
    case 'fig. 5'
        % Data generation parameters
        param       = struct(   'default',false,...
                                'ambient_dims',10, ...
                                'num_samples_bb', 70,...
                                'num_samples_sb', 30,...
                                'common_dims_bb', 3,...
                                'common_dims_sb', 3,...
                                'max_dims', 3,...
                                'big_rad', 1,...
                                'center_sep', (.5)*(1),...
                                'small_rad', (.25)*(.5)*(1),...
                                'noise_var', 0,...
                                'use_subsample', true,...
                                'subsample_percent', .25,...
                                'eq_variance', true,...
                                'int_pts', false,...
                                'int_pts_ratio',1,...
                                'nonuni', false,...
                                'nonuni_amt', 0);
        % Proposed method parameters
        dual_options.tol                    = 10^(-8);
        dual_options.step_type              = 'nonSum-sqSum';
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 200;
        dual_options.per                    = 2;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = false;
        % Primal method parameters [1]
        primal_options.tol                  = 10^(-10);
        primal_options.maxiter              = 1000;       
% ------------------------------------------------------------------------        
    case 'fig. 6'
        % Data generation parameters
        param       = struct(   'default',false,...
                                'ambient_dims',15, ...
                                'num_samples_bb', 100,...
                                'num_samples_sb', 0,...
                                'common_dims_bb', 3,...
                                'common_dims_sb', 3,...
                                'max_dims', 6,...
                                'big_rad', 1,...
                                'center_sep', (.75)*(1),...
                                'small_rad', (.25)*(.75)*(1),...
                                'noise_var', 0,...
                                'use_subsample', false,...
                                'subsample_percent', .25,...
                                'eq_variance', true,...
                                'int_pts', true,...
                                'int_pts_ratio',.5,...
                                'nonuni', true,...
                                'nonuni_amt', 100);
        % Proposed method parameters
        dual_options.tol                    = 10^(-8);
        dual_options.step_type              = 'nonSum-sqSum';
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 200;
        dual_options.per                    = 2;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = false;
        % Primal method parameters [1]
        primal_options.tol                  = 10^(-15);
        primal_options.maxiter              = 2000;       
% ------------------------------------------------------------------------        
    case 'fig. 7a'
        % Data generation parameters
        param           = struct(   'default',false,...
                                    'ambient_dims',10, ...
                                    'num_samples_bb', 30,...
                                    'num_samples_sb', 20,...
                                    'common_dims_bb', 4,...
                                    'common_dims_sb', 4,...
                                    'max_dims', 6,...
                                    'big_rad', 1,...
                                    'center_sep', (.5)*(1),...
                                    'small_rad', (.125)*(.5)*(1),...
                                    'noise_var', 0,...
                                    'use_subsample', false,...
                                    'subsample_percent', .25,...
                                    'eq_variance', true,...
                                    'int_pts', false,...
                                    'int_pts_ratio',1,...
                                    'nonuni', false,...
                                    'nonuni_amt', 50);                        
        % Proposed method parameters
        dual_options.tol                    = 10^(-3);
        dual_options.step_type              = 'nonSum-diminish';%'nonSum-sqSum';%
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 1000;
        dual_options.per                    = 2;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = true;          
% ------------------------------------------------------------------------   
    case 'fig. 7b'
        % Data generation parameters
        param           = struct(   'default',false,...
                                    'ambient_dims',20, ...
                                    'num_samples_bb', 100,...
                                    'num_samples_sb', 0,...
                                    'common_dims_bb', 4,...
                                    'common_dims_sb', 4,...
                                    'max_dims', 6,...
                                    'big_rad', 1,...
                                    'center_sep', (.75)*(1),...
                                    'small_rad', (.25)*(.75)*(1),...%(.25)*(.75)*(.5),...
                                    'noise_var', 0,...
                                    'use_subsample', false,...
                                    'subsample_percent', .5,...
                                    'eq_variance', true,...
                                    'int_pts', false,...
                                    'int_pts_ratio',1,...
                                    'nonuni', true,...
                                    'nonuni_amt', 200);                        
        % Proposed method parameters
        dual_options.tol                    = 10^(-3);
        dual_options.step_type              = 'nonSum-diminish';%'nonSum-sqSum';%
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 1000;
        dual_options.per                    = 2;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = true;
% ------------------------------------------------------------------------  
    case 'fig. 8'
        % Independent variable for this scenario
        indVar            = [20:10:200]; % ambient dimension       
        % Data generation paramters
        param           = struct(   'default',false,...
                                    'ambient_dims',100, ... % Changes each iteration
                                    'num_samples_bb', 10,...
                                    'num_samples_sb', 10,...
                                    'common_dims_bb', 10,...
                                    'common_dims_sb',15,...
                                    'max_dims', 20,...
                                    'big_rad', 1,...
                                    'center_sep', (.5)*(1),...
                                    'small_rad', (.25)*(.5)*(1),...
                                    'noise_var', 1.259,...
                                    'use_subsample', false,...
                                    'eq_variance', false,...
                                    'int_pts', false,...
                                    'nonuni', false);                                                      
        % Proposed method parameters
        dual_options.tol                    = 10^(-4);
        dual_options.step_type              = 'nonSum-diminish';%'nonSum-sqSum';%
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 50;
        dual_options.per                    = 5;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = true;
% ------------------------------------------------------------------------  
    case 'fig. 9'
        % Independent variable for this scenario
        indVar            = [9.4868, 7.5357, 5.9858, 4.7547, 3.7768,...
                        3.0000, 2.3830, 1.8929, 1.5036, 1.1943, 0.9487,...
                        0.7536, 0.5986, 0.4755, 0.3777, 0.3000];  % Noise variance                  
        % Data generation paramters
        param           = struct(   'default',false,...
                                    'ambient_dims', 100, ...
                                    'num_samples_bb', 200,...
                                    'num_samples_sb', 0,...
                                    'common_dims_bb', 3,...
                                    'max_dims', 5,...
                                    'big_rad', 0.5,...
                                    'noise_var', 0.001,... % Changes each iteration
                                    'use_subsample', false,...
                                    'eq_variance', false,...
                                    'int_pts', false,...
                                    'nonuni', true,...
                                    'nonuni_amt', 25);                                              
        % Proposed method parameters
        dual_options.tol                    = 10^(-4);
        dual_options.step_type              = 'nonSum-diminish';%'nonSum-sqSum';%
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 50;
        dual_options.per                    = 5;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = false;
% ------------------------------------------------------------------------  
    case 'fig. 10'
        % Independent variable for this scenario
        indVar            = [5:14,15:5:40]; % ambient dimension       
        % Data generation paramters
        param           = struct(   'default',false,...
                                    'ambient_dims',100, ... % Changes each iteration
                                    'num_samples_bb', 50,...
                                    'num_samples_sb', 0,...
                                    'common_dims_bb', 0,...
                                    'max_dims', 5,...
                                    'big_rad', 1,...
                                    'noise_var', .1259,...
                                    'use_subsample', false,...
                                    'eq_variance', false,...
                                    'int_pts', false,...
                                    'nonuni', false);                                           
        % Proposed method parameters
        dual_options.tol                    = 10^(-4);
        dual_options.step_type              = 'nonSum-diminish';%'nonSum-sqSum';%
        dual_options.useLineSearch          = true;
        dual_options.maxiter                = 50;
        dual_options.per                    = 5;
        dual_options.growth                 = 1.9;
        dual_options.findStationaryPoint    = false;                             
% ------------------------------------------------------------------------   
    otherwise
        error('Unknown scenario'); 
% ------------------------------------------------------------------------        
end

